In [3]:
import numpy as np

Numpy Array

In [4]:
benimListem = [10,20,30]

In [5]:
type(benimListem)

list

In [6]:
#numpy listesi matrix olarak gösterilebilir 
np.array(benimListem)

array([10, 20, 30])

In [7]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
 matrixListesi[1][0]

20

In [9]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

Arange

In [10]:
#python range özelliği hatırlatma amaçlı
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
#numpy arange normal range gibi çalışır
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#0 ile 10 arası sayıları 2 şer olarak yazdır
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Zeros

In [13]:
#bize istediğimiz kadar 0 değeri üretir
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
#bize istediğimiz kadar 1 değeri üretir
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Linspace

In [17]:
#Verilen değerleri eşit parçalara bölecek şekilde yazdırır 0 ile 20 arasındaki rakamları 5 eşit parça olacak şekilde bölüp yazdıralım
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

Eye

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Ramdom

In [19]:
#rastgele doğal sayılar için
np.random.randn(4)

array([-1.99154633,  1.17498623,  0.6625809 , -1.02800264])

In [20]:
np.random.randn(4,4)

array([[ 0.17168035,  1.04521369,  1.74310209, -0.67610014],
       [ 0.64047976,  0.63140903,  0.06187458, -0.11032959],
       [-0.56695517,  0.83502571, -0.08070831,  0.49073257],
       [-0.73139175,  0.34533836, -0.07383682,  0.38998269]])

In [21]:
#rastgele int(tam) sayılar için
np.random.randint(1,10)

4

In [22]:
#rastgele verilen değerlerin kaç adet olacağını belirtmek için üçüncü sayı verilir
np.random.randint(1,100,6)

array([56, 60,  3, 72, 86, 75])

In [24]:
benimNumpyDizim = np.arange(30)

In [25]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
benimRandomDizim = np.random.randint(0,100,12)

In [28]:
benimRandomDizim

array([29, 54, 51, 65, 10, 44, 37, 79, 36, 65, 26, 64])

Numpy Dizi Methodları 

In [29]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [34]:
benimNumpyDizim.max()

np.int64(29)

In [35]:
benimRandomDizim.max()

np.int64(79)

In [36]:
benimRandomDizim.min()

np.int64(10)

In [37]:
benimRandomDizim.argmax()

np.int64(7)

In [38]:
benimRandomDizim.argmin()

np.int64(4)

In [39]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [42]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
reshapeDizim.shape

(5, 6)