In [1]:
import numpy as np

In [2]:
#Numpy arange ile 0 dan 15 e kadar dizi oluşturalım
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
#Beşinci Elemanı Çağıralım
benimDizim[5]

np.int64(5)

In [5]:
#2 ve 6. indeks arasındakileri çağıralım
benimDizim[2:6]

array([2, 3, 4, 5])

In [6]:
#2 ile 6 arasındaki indeks değerlerini değiştirelim
benimDizim[2:6] = -5

In [7]:
benimDizim

array([ 0,  1, -5, -5, -5, -5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
baskaDizi = np.arange(0,24)

In [9]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
#Baska dizideki elemanlardan slicing dizisi oluşturalım ama slicing diziler asıl diziye bağlı tamamen ayrı değil bunu unutma
slicingDizisi = baskaDizi[4:9]

In [11]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [12]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
#Slicing dizisi içindeki elemanları tek tek 700 e eşitleyelim 
slicingDizisi[:] = 700

In [14]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [15]:
#Bu işlemde asıl dizi değişikliğe uğramasın istiyorsak 
ornekDizi = np.arange(0,24)

In [16]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
ornekDiziKopyasi = ornekDizi.copy()

In [18]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]

In [22]:
ornekDiziKopyasiSlicing[:] = 800

In [23]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [24]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [25]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
#Yani Numpy da bir dizi üzerinde çalışıyorsak ve üzerinde değişiklik olmasın istiyorsak onun kopyasını çıkartmak daha sağlıklı olucak.

Matrix

In [27]:
benimListem =[[10,20,30],[30,40,50],[50,60,70]]

In [28]:
benimMatrixDizim = np.array(benimListem)

In [29]:
benimMatrixDizim

array([[10, 20, 30],
       [30, 40, 50],
       [50, 60, 70]])

In [30]:
benimMatrixDizim[0]

array([10, 20, 30])

In [31]:
benimMatrixDizim[1][2]

np.int64(50)

In [32]:
benimMatrixDizim[1,2]

np.int64(50)

In [43]:
benimMatrixDizim[0:,2]

array([30, 50, 70])

In [44]:
 b = np.arange(0,25)

In [45]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
yeniListe = [[0,  1,  2,  3,  4],[5,  6,  7,  8,  9],[10, 11, 12, 13, 14],[15, 16, 17, 18, 19],[20, 21, 22, 23, 24]]

In [48]:
yeniMatrix = np.array(yeniListe)

In [49]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
#
yeniMatrix[[4,0,2]]

array([[20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [59]:
# deneme
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
b.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Operasyonlar

In [68]:
yeniBirDizi = np.random.randint(1,100,20)

In [69]:
yeniBirDizi

array([94, 77, 69, 75, 70, 80, 74, 28, 81, 41, 12, 46, 71, 50, 19,  2, 58,
       15, 55, 74])

In [70]:
yeniBirDizi > 24 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False, False,  True, False,
        True,  True])

In [71]:
 sonucDizisi = yeniBirDizi > 24

In [72]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False, False,  True, False,
        True,  True])

In [73]:
yeniBirDizi

array([94, 77, 69, 75, 70, 80, 74, 28, 81, 41, 12, 46, 71, 50, 19,  2, 58,
       15, 55, 74])

In [75]:
sonucDizisi = yeniBirDizi[yeniBirDizi > 24]

In [76]:
sonucDizisi

array([94, 77, 69, 75, 70, 80, 74, 28, 81, 41, 46, 71, 50, 58, 55, 74])

In [77]:
sonDizi = np.arange(0,24)

In [78]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [80]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [81]:
 sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [82]:
sonDizi / sonDizi

/var/folders/31/hn4_0l4s3rddk6y1ykr7hgym0000gn/T/ipykernel_1261/1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [85]:
#Numpy da karekökünü almak için kullanılır
np.sqrt(sonDizi)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [86]:
np.max(sonDizi)

np.int64(23)

In [87]:
np.min(sonDizi)

np.int64(0)